version: "3"
services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: frontend:latest
        ports:
            - "8081:8081"
        volumes:
            - ./frontend:/app
        labels:
            kompose.service.type: LoadBalancer
    backend:
        container_name: backend
        env_file:
            - .env
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: backend:latest
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/app
        labels:
            kompose.service.type: LoadBalancer